//! Parity test for `Optimizer::BundleAdjustment` (full BA, Schur block solver).
//!
//! Replays the fixture generated by `ORB_SLAM3/tests/optimizer_ba_fixture_gen`
//! (real g2o + BlockSolver_6_3) through the Rust mini-g2o port and asserts the
//! optimized keyframe poses and point positions match.

use std::sync::Arc;

use nalgebra::{Isometry3, Quaternion, Translation3, UnitQuaternion, Vector2, Vector3};

use orb_slam3_rs::camera_models::GeometricCamera;
use orb_slam3_rs::camera_models::pinhole::Pinhole;
use orb_slam3_rs::optimizer::{BaKeyframe, BaObs, bundle_adjustment_core};

fn data_lines(text: &str) -> Vec<String> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_string)
        .collect()
}

fn nums(line: &str) -> Vec<f64> {
    line.split_whitespace()
        .map(|s| s.parse().unwrap())
        .collect()
}

fn parse_pose(v: &[f64]) -> Isometry3<f32> {
    let q = UnitQuaternion::new_normalize(Quaternion::new(v[0], v[1], v[2], v[3]));
    Isometry3::from_parts(
        Translation3::new(v[4] as f32, v[5] as f32, v[6] as f32),
        q.cast::<f32>(),
    )
}

#[test]
fn bundle_adjustment_matches_g2o() {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/bundle_adjustment.txt"
    ))
    .expect("fixture present (run optimizer_ba_fixture_gen)");
    let lines = data_lines(&text);
    let mut it = lines.iter();

    let intr = nums(it.next().unwrap());
    let (fx, fy, cx, cy, bf) = (intr[0], intr[1], intr[2], intr[3], intr[4]);
    let camera: Arc<dyn GeometricCamera> = Arc::new(Pinhole::with_params(vec![
        fx as f32, fy as f32, cx as f32, cy as f32,
    ]));

    let n_kf: usize = it.next().unwrap().parse().unwrap();
    let mut keyframes = Vec::with_capacity(n_kf);
    for _ in 0..n_kf {
        let v = nums(it.next().unwrap());
        keyframes.push(BaKeyframe {
            pose: parse_pose(&v[1..8]),
            fixed: v[0] == 1.0,
            camera: camera.clone(),
            fx,
            fy,
            cx,
            cy,
            bf,
        });
    }

    let n_mp: usize = it.next().unwrap().parse().unwrap();
    let mut points = Vec::with_capacity(n_mp);
    for _ in 0..n_mp {
        let v = nums(it.next().unwrap());
        points.push(Vector3::new(v[0], v[1], v[2]));
    }

    let n_obs: usize = it.next().unwrap().parse().unwrap();
    let mut observations = Vec::with_capacity(n_obs);
    for _ in 0..n_obs {
        let v = nums(it.next().unwrap());
        let (kf, mp) = (v[1] as usize, v[2] as usize);
        let inv_sigma2 = v[6];
        if v[0] == 0.0 {
            observations.push(BaObs::Mono {
                kf,
                mp,
                obs: Vector2::new(v[3], v[4]),
                inv_sigma2,
            });
        } else {
            observations.push(BaObs::Stereo {
                kf,
                mp,
                obs: Vector3::new(v[3], v[4], v[5]),
                inv_sigma2,
            });
        }
    }

    let ref_poses: Vec<Isometry3<f32>> = (0..n_kf)
        .map(|_| parse_pose(&nums(it.next().unwrap())))
        .collect();
    let ref_points: Vec<Vector3<f64>> = (0..n_mp)
        .map(|_| {
            let v = nums(it.next().unwrap());
            Vector3::new(v[0], v[1], v[2])
        })
        .collect();

    let (poses, pts) = bundle_adjustment_core(&keyframes, &points, &observations, 20, true);

    for (i, (got, exp)) in poses.iter().zip(ref_poses.iter()).enumerate() {
        let dr = got.rotation.angle_to(&exp.rotation);
        let dt = (got.translation.vector - exp.translation.vector).norm();
        assert!(dr < 1e-6, "KF {i} rotation differs by {dr} rad");
        assert!(dt < 1e-6, "KF {i} translation differs by {dt}");
    }
    for (i, (got, exp)) in pts.iter().zip(ref_points.iter()).enumerate() {
        let d = (got - exp).norm();
        assert!(d < 1e-5, "MP {i} differs by {d}");
    }
}
