//! Parity test for `Optimizer::PoseOptimization`.
//!
//! Replays the fixture generated by `ORB_SLAM3/tests/optimizer_pose_fixture_gen`
//! (real g2o) through the Rust mini-g2o port and asserts the optimized pose,
//! inlier classification, and inlier count match.

use std::sync::Arc;

use nalgebra::{Isometry3, Quaternion, Translation3, UnitQuaternion, Vector2, Vector3};

use orb_slam3_rs::camera_models::GeometricCamera;
use orb_slam3_rs::camera_models::pinhole::Pinhole;
use orb_slam3_rs::optimizer::{PoseObs, pose_optimization_core};

/// Strip comment lines (starting with `#`) and return the data tokens.
fn data_lines(text: &str) -> Vec<String> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_string)
        .collect()
}

fn parse_pose(line: &str) -> Isometry3<f32> {
    let v: Vec<f64> = line
        .split_whitespace()
        .map(|s| s.parse().unwrap())
        .collect();
    let q = UnitQuaternion::new_normalize(Quaternion::new(v[0], v[1], v[2], v[3]));
    Isometry3::from_parts(
        Translation3::new(v[4] as f32, v[5] as f32, v[6] as f32),
        q.cast::<f32>(),
    )
}

#[test]
fn pose_optimization_matches_g2o() {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/pose_optimization.txt"
    ))
    .expect("fixture present (run optimizer_pose_fixture_gen)");
    let lines = data_lines(&text);

    let mut it = lines.iter();
    let intr: Vec<f64> = it
        .next()
        .unwrap()
        .split_whitespace()
        .map(|s| s.parse().unwrap())
        .collect();
    let (fx, fy, cx, cy, bf) = (intr[0], intr[1], intr[2], intr[3], intr[4]);

    let init_pose = parse_pose(it.next().unwrap());
    let n: usize = it.next().unwrap().parse().unwrap();

    let mut observations = Vec::with_capacity(n);
    for i in 0..n {
        let v: Vec<f64> = it
            .next()
            .unwrap()
            .split_whitespace()
            .map(|s| s.parse().unwrap())
            .collect();
        let kind = v[0] as i32;
        let xw = Vector3::new(v[1], v[2], v[3]);
        let inv_sigma2 = v[7];
        if kind == 0 {
            observations.push(PoseObs::Mono {
                xw,
                obs: Vector2::new(v[4], v[5]),
                inv_sigma2,
                idx: i,
            });
        } else {
            observations.push(PoseObs::Stereo {
                xw,
                obs: Vector3::new(v[4], v[5], v[6]),
                inv_sigma2,
                idx: i,
            });
        }
    }

    let ref_pose = parse_pose(it.next().unwrap());
    let ref_inliers: i32 = it.next().unwrap().parse().unwrap();
    let ref_flags: Vec<bool> = it
        .next()
        .unwrap()
        .split_whitespace()
        .map(|s| s == "1")
        .collect();

    let camera: Arc<dyn GeometricCamera> = Arc::new(Pinhole::with_params(vec![
        fx as f32, fy as f32, cx as f32, cy as f32,
    ]));

    let (pose, n_inliers, flags) =
        pose_optimization_core(init_pose, &camera, None, fx, fy, cx, cy, bf, &observations);

    // Inlier classification must match exactly.
    let got_flags: Vec<bool> = flags.iter().map(|(_, b)| *b).collect();
    assert_eq!(got_flags, ref_flags, "outlier classification differs");
    assert_eq!(n_inliers, ref_inliers, "inlier count differs");

    // Optimized pose: compare rotation + translation tightly.
    let dr = pose.rotation.angle_to(&ref_pose.rotation);
    let dt = (pose.translation.vector - ref_pose.translation.vector).norm();
    assert!(dr < 1e-6, "rotation differs by {dr} rad");
    assert!(dt < 1e-6, "translation differs by {dt}");
}
